version: "3"
services:
  app:
    container_name: node-mysql-start
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mysql-db
  mysql-db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce-shop
      MYSQL_USER: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
  client:
    image: mysql/mysql-server:8.0
    depends_on:
      - mysql-db
    command: mysql -uroot -ppassword -hmysql-db ecommerce-shop
