version: "3"
services:
  app:
    container_name: docker-node-mysql
    restart: always
    build: .
    links:
      - mysql
    ports:
      - "5000:3000"

  mysql:
    container_name: mysql
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: node_complete_guide

  client:
    image: mysql/mysql-server
    depends_on:
      - mysql
    command: mysql -uroot -ppassword -hmysql node_complete_guide
